CREATE TABLE TC_DEVICE(
ID INTEGER AUTO_INCREMENT PRIMARY KEY
VERSION VARCHAR(20),
SYSTEM VARCHAR(20),
MACHINE VARCHAR(20),
BUILD_NAME VARCHAR(20),
NODE VARCHAR(20),
COMPILER VARCHAR(20),
KERNEL VARCHAR(20),
PLATFORM VARCHAR(20),
BUILD_DATE VARCHAR(20),
PLATFORM_NAME VARCHAR(20)
)
