CREATE TABLE TC_DEVICE(
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
DEVICE_IDENTIFIER VARCHAR(100),
VERSION VARCHAR(20),
SYSTEM VARCHAR(100),
MACHINE VARCHAR(100),
BUILD_NAME VARCHAR(100),
NODE VARCHAR(100),
COMPILER VARCHAR(100),
KERNEL VARCHAR(100),
PLATFORM VARCHAR(100),
BUILD_DATE VARCHAR(100),
PLATFORM_NAME VARCHAR(100)
)
